### ISSUE TITLE
Not a issue, but 2 screenshots for your mod page

### ISSUE THREAD

**Issue by LuziferSenpai** [vsaulue/factorio-dana#2]
[Pure Angels - Full Tree](https://i.imgur.com/V6tDNvZ.png)
[Pure Angels - White Analyzers](https://i.imgur.com/GM5MldN.png)

**Comment by vsaulue** [comment]
Hi, thanks for testing & the pictures.

However I'm not sure this would be a very good front cover for Dana right now. On one's hand it's good that it is able to plot something technically correct on a big overhaul modpack, on the other hand the result is impossible to understand (= useless).

There are still a lot of ways to improve the layout/renderer to help on this issue. But even with all the ideas I could ever have, I'm pretty sure I'll never be able to render anything understandable from the _full_ Angel&Bob crafting tree.
